name: farmer_market
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#    internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  intl_utils: 2.6.1

# firebase
  cloud_firestore: ^3.1.4
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_storage: ^10.2.3

# serialization
  json_serializable: 6.1.4
  json_annotation: 4.4.0

# get_it:
  get_it: ^7.2.0

#  net
  retrofit: ^3.0.0

# images:
  image_picker: ^0.8.4+4

#bloc
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

#  storage
  shared_preferences: ^2.0.13

#freezed
  freezed: 1.1.0

#location and address
  geolocator: ^8.2.0
  geocoding: ^2.0.2

# various
  uuid: ^3.0.5
  cached_network_image: 3.2.0
  flutter_verification_code: 1.1.2
  cupertino_icons: ^1.0.2
  logger: any


dev_dependencies:
  retrofit_generator: '<4.0.0'
  flutter_test:
    sdk: flutter
  build_runner:

  bloc_test: ^9.0.0
  mocktail: ^0.2.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Light.ttf
flutter_intl:
  defaultLocale: en_US
  enabled: true


